# Site settings
title: Dizzy Land
email: xxx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shawn Zhang's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shawn11zx.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  shawn11ZX

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font