---
layout: post
title: Book Reading - How to Read a Book
---

:toc: macro
:toclevels: 4
:sectnums:
:imagesdir: /images
:hp-tags: Reading, Book

toc::[]

__How to Read a Book __ is written by the American philosopher Mortimer J. Adler. It can be classified into the category of *Practical Books*. 

In a nutshell, this book tries to help improve people's ability of reading books. It states that before reading any book there are four questions each reader must ask themselves: 

- What is the book about as a whole
- What is been said in detail and how
- Is the book true, in whole and part
- How is the book related to you? 

By dividing people's ability of reading into the following four different but highly related levels, the author helps us find ways as to how to answer the above four questions.

 - elementary reading
 - inspectional reading
 - analytical reading
 - syntopical reading

The book is consists of four parts with each part have several chapters.

== PART ONE: THE DIMENSIONS OF READING. 

Given the same book, different reader can have very different gains. The difference is mainly caused by reader's active attitudes and reading skills. The more effort we put on reading the more understanding we can obtain from it. 

There are four levels of reading, each lower level is included in higher level. That is the higher the level one is choosing, the more effort he will need to pay, and finally the more comprehension he can get from the reading activity.

=== elementary reading

The first and lowest level of reading is *elementary reading*. The purpose of this level is answer the question: What is the meaning of the sentences. This level can be further divided into four stages:

1. reading readiness, corresponding to pre-school experiences.
2. word mastery
3. vocabulary growth and utilization of context
4. functional literacy. 

At the final stage, children can read traffic signs or picture captions fairly easy. They are considered mature readers and can almost read any kinds of books.

=== inspectional reading
 
The second level of reading is *inspectional reading*, which answers the question: what the book is about as a whole. It can be divided into two steps:

Step one is *systematic skimming* or pre-reading. By going through title, preface, table of content, index, publisher's blurb, and some intentionally chosen chapters or paragraphs one can get a brief impression of the book and be able to classify it. We should consider ourselves as detectives looking for clues to a book's general theme or idea.

Step two is *superficial reading*. The trick is to read from front to end with as little pause as possible, without looking up dictionaries, encyclopedia or thing alike. As the author said, trying to understand every detail at this stage can easily destroy your interest and curiosity in this book. Even if you are not going to read it again, reading a whole book without total understanding is better than never read it through.

=== Demanding Readers

To be good at reading, one need to be active. To be active, the trick is to first ask the above mentioned four questions and then find answers as you read.

During reading, we can also make marks on the book to:

- keep us awake
- help us clearly express our understanding and ideas
- help us remember author's ideas.

[quote]
____
The person who says he knows what he thinks but cannot express it usually does not know what he thinks.
____

== PART TWO: Analytical reading

Analytical reading contains three phases, each of which emphasizes several rules.

- Phase 1 answers the question "What is the book about as a whole"
* Rule #1: Classify a Book
* Rule #2: Summarize the content of the book with one sentence
* Rule #3: List the outline of the book
* Rule #4: Find out the questions the author tries to answer in the book

- Phase 2 answers the question "What is been said in detail and how"
* Rule #5: For keywords, find out the exact definition
* Rule #6: Find out key proposals that result in the main idea of the book
* Rule #7: Figure out how these proposals are proven in the book.
* Rule #8: Of the questions in Rule #4, make clear what of these are answered and what are not. Of the unanswered questions, what are recognized by the author.

- Phase 3 answers the 3rd one by making remarks about the book
* Rule #9: Fully understand the book before making any judgement.
* Rule #10: Don't be aggressive
* Rule #11: Differentiate between knowledge and opinion before remarking

If you want to make criticisms:

* Rule #12: prove that the author's knowledge is not adequate
* Rule #13: prove that the author's knowledge is wrong
* Rule #13: prove that the author is illogical
* Rule #13: prove that the author's analysis or reasoning is inadequate

=== Classifying a Book
The first step of analytical reading is find the category of the book you are about to read, the earlier the better.

Books can be first classified into two categories: *expository* or *fiction*. The purpose of expository book is to convey knowledge. 

We may or may not find hinds about a book's category from its title.

Expository books can be further split into two kinds: *practical* and *theoretical*. The former focuses on HOW, while the later concentrates on WHAT.

Examples of practical books include:

- engineering
- medical
- cooking

Not only do practical books tells us HOW, they usually spend a lot of effort persuade us to follow their instructions. After all, a practical book that is not followed by its readers is actually mean-less.

Common words in practical books includes: should, ought, good or bad.

Examples of theoretical books include:

- history, describes true events happened at specific locations in specific time periods.
- science, which is about general truth, most of which can't be easily verified in our daily life but rather based on accurate observations or experiments.
- philosophy, which can't usually drift too far away from our daily experiences.

=== Questions of the author
At the beginning of writing, writers usually has one or more questions, which they answer in the book.

For practical books, questions may be like:

- What ends should be sought?
- What means should be chosen to a given end?
- Under given conditions, what's better? what's right? what's worse? 

For theoretical books, these are example questions:

- Does something exist?
- What kind of thing is it?
- What's the effect?

=== Keywords
No language is perfect. Every words can have several meanings and every meaning can be conveied by more than one word. That why we need to reach a common defination of the keywords in the book with the author.

Personally, that's why I find it's sometimes more easy to read the original version of a book even if it's written in a foreign langure, than to read a translated book in my native language. Because during translation, if the translators are a little careless, meanings of keywords will be mistranslated.

== PART THREE: syntopical reading
Synotopical reading is usually applied to reading of social science books. Since it's relatively hard to find a main authentic book of a given subject, we need to read and compare several books to understand the subject. 